AWSTemplateFormatVersion: 2010-09-09
Parameters:
    LambdaName:
        Description: Llave
        Type: String
    LambdaRuntime:
       Description: Runtime
       Type: String
       Default: python3.7
       AllowedValues:
        - dotnetcore1.0
        - dotnetcore2.0
        - dotnetcore2.1
        - dotnetcore3.1
        - go1.x
        - java11
        - java8
        - java8.al2
        - nodejs
        - nodejs10.x
        - nodejs12.x
        - nodejs14.x
        - nodejs4.3
        - nodejs6.10
        - nodejs8.10
        - python3.6
        - python3.7
        - python3.8
        - python3.9
        - ruby2.5
        - ruby2.7
    LambdaBucket:
        Description: Bucket
        Type: String
    ZipName:
        Description: Zip
        Type: String        
Resources:
    api:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: lambda
        Properties:
            TemplateURL: https://labts.s3.us-west-2.amazonaws.com/api.yml 
            Parameters:
                LambdaFunction: !GetAtt lambda.Outputs.LambdaFunction        
    lambda:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://labts.s3.us-west-2.amazonaws.com/lambda.yml
            Parameters:
                LambdaName: !Ref LambdaName
                LambdaRuntime: !Ref LambdaRuntime
                LambdaBucket: !Ref LambdaBucket  
                ZipName: !Ref ZipName           